### PR TITLE
Give the `Readme` and `License` files reasonable names

### PR DESCRIPTION
**Pull request by rdancer**
Github now parses both files with Markdown for display.

While reasonable people may disagree what the proper extension may be
for a Markdown source file, the `Readme` should not include the project
name in its name.

### CODE REVIEW

**Comment by rdancer** [comment]
The files are not parsed well by Github-flavoured Markdown; let me fix that and re-submit

**Comment by michelf** [comment]
I don't plan to rename the file in the current distribution to accommodate Github's standard.

What I plan to do is [what I did for PHP Markdown](http://michelf.ca/blog/2013/php-markdown-lib/): create a new package in a separate `lib` branch, this one with a Github friendly readme file, and make that branch the default branch.

**Comment by rdancer** [comment]
Making it similar with php-markdown was exactly my thought.  Would you be
happy with my updating the files' markup to parse well on Github?

Also, I am struggling to use both php-markdown and php-smartypants at the
same time; is this supported?  The Readme doesn't mention it.

**Comment by michelf** [comment]
Well, I'm curious about what those changes would be. But if I do as I did for PHP Markdown, I'm probably going to change half of the readme file as I transition to a separate `lib` branch, so it might be a wasted effort to fix the file. So I don't know.

Using both at the same time is easy: pass the input through Markdown, then pass the result through Smartypants. There's a mention of it in the PHP Markdown readme.

**Pull request closed without merging**
